version: "3.8"

services:
  db:
    container_name: "<container_name>"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "<database_name>"
      POSTGRES_USER: "<database_user>"
      POSTGRES_PASSWORD: "<database_password>"
    restart: unless-stopped
